# Autogenerated wrapper script for picotool_jll for x86_64-linux-gnu
export pico_udev, picotool

using libusb_jll
JLLWrappers.@generate_wrapper_header("picotool")
JLLWrappers.@declare_file_product(pico_udev)
JLLWrappers.@declare_executable_product(picotool)
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll)
    JLLWrappers.@init_file_product(
        pico_udev,
        "99-picotool.rules",
    )

    JLLWrappers.@init_executable_product(
        picotool,
        "bin/picotool",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
